package com.meetspace.service;
import com.meetspace.dto.AuthDtos.*; import com.meetspace.exception.ApiException; import com.meetspace.model.UserAccount; import com.meetspace.repository.UserRepository; import com.meetspace.security.UserPrincipal; import org.springframework.beans.factory.annotation.Value; import org.springframework.http.HttpStatus; import org.springframework.security.crypto.password.PasswordEncoder; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.nio.charset.StandardCharsets; import java.security.*; import java.util.*;
@Service public class AuthService { private final org.springframework.context.ApplicationEventPublisher events; private final UserRepository users; private final PasswordEncoder passwords; private final int verificationHours, resetMinutes; private final String frontendBaseUrl; private final SecureRandom random=new SecureRandom(); public AuthService(UserRepository u,PasswordEncoder p,org.springframework.context.ApplicationEventPublisher e,@Value("${meetspace.security.verification-token-hours}") int v,@Value("${meetspace.security.reset-token-minutes}") int r,@Value("${meetspace.frontend-base-url}") String base){users=u;frontendBaseUrl=base;events=e;passwords=p;verificationHours=v;resetMinutes=r;}
 @Transactional public void register(RegisterRequest r){String email=r.email().trim().toLowerCase(Locale.ROOT);if(users.findByEmail(email).isPresent())throw new ApiException(HttpStatus.CONFLICT,"EMAIL_ALREADY_EXISTS","An account with this email already exists");String[] names=r.fullName().trim().split("\\s+",2);if(names.length<2)throw new ApiException(HttpStatus.BAD_REQUEST,"VALIDATION_ERROR","Full name must include first and last name");UUID id=users.createUser(email,passwords.encode(r.password()));users.createEmployee(id,r.employeeId().trim(),names[0],names[1],r.department().trim());String raw=token();users.createVerification(id,hash(raw),verificationHours);publishMail(email,"Verify your MeetSpace account","Verify your account: "+link("/verify-email?token="+raw));}
 public UserPrincipal login(LoginRequest r){UserAccount u=users.findByEmail(r.email().trim()).orElseThrow(()->new ApiException(HttpStatus.UNAUTHORIZED,"INVALID_CREDENTIALS","Invalid email or password"));if(!passwords.matches(r.password(),u.passwordHash()))throw new ApiException(HttpStatus.UNAUTHORIZED,"INVALID_CREDENTIALS","Invalid email or password");if(!u.active())throw new ApiException(HttpStatus.FORBIDDEN,"ACCOUNT_INACTIVE","This account is inactive");if(!u.emailVerified())throw new ApiException(HttpStatus.FORBIDDEN,"EMAIL_NOT_VERIFIED","Verify your email before signing in");return new UserPrincipal(u.id(),u.email(),u.role());}
 @Transactional public void verify(String raw){UUID id=users.consumeVerification(hash(raw)).orElseThrow(()->new ApiException(HttpStatus.BAD_REQUEST,"INVALID_OR_EXPIRED_TOKEN","This verification link is invalid or expired"));users.markVerified(id);}
 @Transactional public void forgot(ForgotPasswordRequest r){users.findByEmail(r.email().trim()).filter(UserAccount::active).ifPresent(u->{String raw=token();users.createReset(u.id(),hash(raw),resetMinutes);publishMail(u.email(),"Reset your MeetSpace password","Reset your password: "+link("/reset-password?token="+raw));});}
 @Transactional public void reset(ResetPasswordRequest r){UUID id=users.consumeReset(hash(r.token())).orElseThrow(()->new ApiException(HttpStatus.BAD_REQUEST,"INVALID_OR_EXPIRED_TOKEN","This reset link is invalid or expired"));users.updatePassword(id,passwords.encode(r.password()));}
 public UserResponse current(UserPrincipal p){var u=users.findById(p.id()).orElseThrow(()->new ApiException(HttpStatus.UNAUTHORIZED,"AUTH_REQUIRED","Authentication is required"));return safe(u);} public UserResponse safe(UserAccount u){return new UserResponse(u.id(),u.email(),u.role(),u.emailVerified());} private void publishMail(String to,String subject,String body){events.publishEvent(new com.meetspace.notification.EmailNotification(to,subject,body));} private String link(String path){return frontendBaseUrl+path;} private String token(){byte[] b=new byte[32];random.nextBytes(b);return Base64.getUrlEncoder().withoutPadding().encodeToString(b);} private String hash(String value){try{return HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(value.getBytes(StandardCharsets.UTF_8)));}catch(NoSuchAlgorithmException e){throw new IllegalStateException(e);}}
}