"use client";
import {Canvas} from "@react-three/fiber"; import {OrbitControls,Text} from "@react-three/drei"; import Link from "next/link"; import {useQuery} from "@tanstack/react-query"; import {useState} from "react"; import {roomApi} from "@/services/rooms"; import {bookingApi} from "@/services/bookings"; import type {Room} from "@/types/domain";
type Scope={date:string;start:string;end:string}; type Status="AVAILABLE"|"UNAVAILABLE"|"INACTIVE"|"CHECKING";
const today=()=>new Date().toISOString().slice(0,10);
export function OfficeWorkspace(){const [scope,setScope]=useState<Scope>({date:today(),start:"10:00",end:"11:00"});const [selected,setSelected]=useState<Room|null>(null);const rooms=useQuery({queryKey:["rooms"],queryFn:roomApi.list});const valid=scope.date&&scope.start&&scope.end&&scope.start<scope.end;return <main className="min-h-screen bg-paper px-5 py-10 text-ink"><section className="mx-auto max-w-6xl"><p className="font-mono text-xs uppercase tracking-wider text-work-blue">Office map</p><h1 className="mt-2 text-3xl font-semibold">Meeting room office</h1><p className="mt-2 text-slate">Choose a time to see authoritative room availability.</p><Controls scope={scope} setScope={setScope}/>{!valid&&<p role="alert" className="mt-3 text-sm text-red-700">End time must be after start time.</p>}<Office rooms={rooms.data?.data??[]} scope={scope} enabled={Boolean(valid)} selected={selected} select={setSelected}/><Directory rooms={rooms.data?.data??[]} scope={scope} enabled={Boolean(valid)} selected={selected} select={setSelected}/></section></main>}
function Controls({scope,setScope}:{scope:Scope;setScope:(s:Scope)=>void}){return <div className="mt-6 grid gap-3 border-y border-line bg-white p-4 sm:grid-cols-3">{(["date","start","end"] as const).map(key=><label key={key} className="text-sm font-semibold">{key==="date"?"Date":key==="start"?"Start":"End"}<input type={key==="date"?"date":"time"} min={key==="date"?today():undefined} value={scope[key]} onChange={e=>setScope({...scope,[key]:e.target.value})} className="mt-1 block w-full border border-line px-3 py-2" required/></label>)}</div>}
function useRoomStatus(room:Room,scope:Scope,enabled:boolean){const q=useQuery({queryKey:["availability",room.id,scope.date,scope.start,scope.end],queryFn:()=>bookingApi.availability(room.id,scope.date,scope.start,scope.end),enabled:enabled&&room.active});return !room.active?"INACTIVE":!enabled?"CHECKING":q.data?.data.available?"AVAILABLE":q.data?"UNAVAILABLE":"CHECKING"}
function Office({rooms,scope,enabled,selected,select}:{rooms:Room[];scope:Scope;enabled:boolean;selected:Room|null;select:(r:Room)=>void}){return <div className="mt-6 h-[420px] border border-line bg-white" role="img" aria-label="Interactive 3D office map; the room directory below provides the accessible alternative."><Canvas camera={{position:[8,10,12],fov:45}}><ambientLight intensity={1.5}/><directionalLight position={[5,8,5]} intensity={2}/><mesh rotation={[-Math.PI/2,0,0]}><planeGeometry args={[18,14]}/><meshStandardMaterial color="#e7e5e4"/></mesh>{rooms.map((room,index)=><RoomMesh key={room.id} room={room} index={index} scope={scope} enabled={enabled} selected={selected?.id===room.id} select={select}/>) }<OrbitControls enableDamping minDistance={8} maxDistance={22} maxPolarAngle={Math.PI/2.15}/></Canvas></div>}
function RoomMesh({room,index,scope,enabled,selected,select}:{room:Room;index:number;scope:Scope;enabled:boolean;selected:boolean;select:(r:Room)=>void}){const s=useRoomStatus(room,scope,enabled);const x=index%2===0?-5:5,z=Math.floor(index/2)*3-4,color=selected?"#1f4e79":s==="AVAILABLE"?"#9fb9cc":s==="UNAVAILABLE"?"#cbd5e1":"#94a3b8";return <group position={[x,1,z]} onClick={()=>select(room)}><mesh><boxGeometry args={[5,2,2.4]}/><meshStandardMaterial color={color}/></mesh><Text position={[0,1.2,0]} fontSize={.32} color="#172554" anchorX="center" anchorY="middle">{room.roomCode+" "+s}</Text></group>}
function Directory({rooms,scope,enabled,selected,select}:{rooms:Room[];scope:Scope;enabled:boolean;selected:Room|null;select:(r:Room)=>void}){return <div className="mt-6 grid gap-6 lg:grid-cols-[1fr_20rem]"><div><h2 className="text-lg font-semibold">Room directory</h2><div className="mt-3 divide-y border-y border-line bg-white">{rooms.map(room=><Row key={room.id} room={room} scope={scope} enabled={enabled} select={select}/>)}</div></div><Details room={selected} scope={scope} enabled={enabled}/></div>}
function Row({room,scope,enabled,select}:{room:Room;scope:Scope;enabled:boolean;select:(r:Room)=>void}){const s=useRoomStatus(room,scope,enabled);return <button onClick={()=>select(room)} className="grid w-full grid-cols-[7rem_1fr_auto] gap-3 px-4 py-3 text-left hover:bg-slate-50"><span className="font-mono text-sm text-work-blue">{room.roomCode}</span><span>{room.name}</span><span className="text-sm text-slate">{s}</span></button>}
function Details({room,scope,enabled}:{room:Room|null;scope:Scope;enabled:boolean}){const s=useRoomStatus(room??({id:"inactive",active:false} as Room),scope,enabled&&Boolean(room));return <aside className="border-l-2 border-work-blue bg-white p-5" aria-live="polite"><h2 className="text-lg font-semibold">{room?.name??"Select a room"}</h2>{room?<><p className="mt-2 text-sm text-slate">{room.roomCode} · Floor {room.floor} · {room.capacity} seats</p><p className="mt-3 text-sm text-slate">{room.facilities.join(", ")||"No facilities listed."}</p><p className="mt-3 text-sm text-slate">{scope.date} · {scope.start} – {scope.end}</p><p className="mt-2 text-sm font-semibold">Status: {s==="UNAVAILABLE"?"Unavailable for selected time":s}</p><Link href={`/rooms/${room.id}`} className="mt-5 inline-block text-sm font-semibold text-work-blue underline">View room details</Link></>:<p className="mt-2 text-sm text-slate">Choose a room from the directory or map.</p>}</aside>}
